### ISSUE TITLE
[BUG] 'DummyCatalogSource' object has no attribute 'get_driver' in 01.Getting_Started.ipynb

### ISSUE THREAD

**Issue by hackelle** [merantix-momentum/squirrel-datasets-core#33]
When running the first two cells of the [getting started notebook](https://github.com/merantix-momentum/squirrel-datasets-core/blob/main/examples/01.Getting_Started.ipynb), I get the AttributeError shown above.

squirrel 0.12.3
squirrle-datasets 0.1.2
google-colab (CPU Runtime)

Expected behavior: getting CIFAR dataset to be able to show it using matplotlib

Side note: Comment says "imagenet" but code says "cifar10" (cell 2, line 10)

**Comment by AlpAribal** [comment]
Thank you for the bug report! Could you try restarting the Colab runtime (Runtime -> Restart runtime) after installing squirrel-datasets-core and re-run the cells?

We will be fixing the typos in the meantime.

**Comment by hackelle** [comment]
Thank you, that solved my problem
