### ISSUE TITLE
[BUG] Linting instruction are missing

### ISSUE THREAD

**Issue by jotterbach** [merantix-momentum/squirrel-datasets-core#57]
Before you open an issue, please check if a similar issue already exists or has been closed before.

 ### When reporting a bug, please be sure to include the following:
 - [ ] A descriptive title
 - [ ] An *isolated* way to reproduce the behavior (example: GitHub repository with code isolated to the issue that anyone can clone to observe the problem)
 - [ ] What version of `squirrel-datasets` and `squirrel` you're using, and the platform(s) you're running it on
 - [ ] What packages or other dependencies you're using
 - [ ] The behavior you expect to see and the actual behavior

 See [contributing guideline]() for more detail on what is expected of a bug report.

PR #56 (https://github.com/merantix-momentum/squirrel-datasets-core/pull/56) is failing. The error is due to liniting. However, there is not linting instructions for the contribution guidelines. In fact there is no link to the contributions guideline in the README of the repo

**Comment by winfried-ripken** [comment]
Thank you for pointing this out! There will be a major documentation update in the next few days, and I will include this in there.
